[package]
name = "shader"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib","cdylib"]
path = "src/main.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kinc = {path = "../../kinc"}
krafix = {path = "../../krafix"}