name: Build

on: [push]

jobs:
  build:
    if: ${{ !contains(join(github.event.commits.*.message),'[skip ci]') }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
            graphics: metal
          # - os: macos-latest
          #   target: aarch64-apple-ios
          #   graphics: metal
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            graphics: d3d11
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            graphics: d3d12
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            graphics: opengl
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            graphics: opengl
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            graphics: vulkan
          # - os: ubuntu-latest
          #   target: aarch64-linux-android
          #   graphics: opengl
          # - os: ubuntu-latest
          #   target: aarch64-linux-android
          #   graphics: vulkan
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          profile: minimal
          override: true
          components: clippy

      - uses: Swatinem/rust-cache@v1

      - name: Get submodules
        run: |
          git submodule update --init
          kinc/Kinc/get_dlc
          git -C krafix/krafix submodule update --init --depth 1

      - name: Install Ubuntu packages
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev libxinerama-dev libxrandr-dev libgl1-mesa-dev libxi-dev libxcursor-dev libudev-dev libwayland-dev wayland-protocols libxkbcommon-dev libvulkan-dev --yes --quiet

      - run: |
          cargo check -p shader --features=kinc/${{ matrix.graphics }} --target=${{ matrix.target }}
