[package]
name = "kinc"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "1.3.2"
krafix = {path = "../krafix"}

[build-dependencies]
bindgen = "0.59.2"
cc = { version ="1.0.73", features = ["parallel"] }

[features]
vulkan = []
opengl = []
metal = []
d3d11 = []
d3d12 = []
std = []
